- name: Change master-1 name
  hostname:
    name: k8s-master-1.cloudservices.int
  when: inventory_hostname in groups['control_plane_1']

- name: Change master-2 name
  hostname:
    name: k8s-master-2.cloudservices.int
  when: inventory_hostname in groups['control_plane_2']

- name: Change master-3 name
  hostname:
    name: k8s-master-3.cloudservices.int
  when: inventory_hostname in groups['control_plane_3']

- name: Change compute-1 name
  hostname:
    name: k8s-compute-1.cloudservices.int
  when: inventory_hostname in groups['worker1']

- name: Change compute-2 name
  hostname:
    name: k8s-compute-2.cloudservices.int
  when: inventory_hostname in groups['worker2']
