- name: Deploy Kubernetes Dashboard
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.40.1/deploy/static/provider/cloud/deploy.yaml
  when: inventory_hostname in groups['control_plane_1']